name: Publish

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install set-version
        run: cargo install cargo-edit

      - name: Bump version
        run: cargo set-version ${{ github.ref_name }}

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.3
        with:
          add: "Cargo.toml"
          message: "chore: bump version ${{ github.ref_name }}"
          push: true
          default_author: github_actions
          new_branch: master

      - name: Publish
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
